//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerFirmEntities : DbContext
    {
        public ComputerFirmEntities()
            : base("name=ComputerFirmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BrandHardware> BrandHardwares { get; set; }
        public DbSet<InfoFirm> InfoFirms { get; set; }
        public DbSet<InfoHardware> InfoHardwares { get; set; }
        public DbSet<OrdersExecute> OrdersExecutes { get; set; }
        public DbSet<OrdersFirm> OrdersFirms { get; set; }
        public DbSet<OrdersUser> OrdersUsers { get; set; }
        public DbSet<Table> Tables { get; set; }
        public DbSet<TypeHardware> TypeHardwares { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
