//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoHardware
    {
        public InfoHardware()
        {
            this.OrdersFirms = new HashSet<OrdersFirm>();
            this.OrdersUsers = new HashSet<OrdersUser>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> numbAvailable { get; set; }
        public Nullable<int> numbOrder { get; set; }
        public Nullable<int> cost { get; set; }
        public string fname { get; set; }
        public int typeId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string describe { get; set; }
    
        public virtual BrandHardware BrandHardware { get; set; }
        public virtual TypeHardware TypeHardware { get; set; }
        public virtual ICollection<OrdersFirm> OrdersFirms { get; set; }
        public virtual ICollection<OrdersUser> OrdersUsers { get; set; }
    }
}
