//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoFirm
    {
        public InfoFirm()
        {
            this.OrdersFirms = new HashSet<OrdersFirm>();
        }
    
        public int Id { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<OrdersFirm> OrdersFirms { get; set; }
    }
}
