//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersUser
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public int numb { get; set; }
        public int HardwareId { get; set; }
        public int UserId { get; set; }
        public int ExecuteId { get; set; }
        public Nullable<System.DateTime> dateExecution { get; set; }
    
        public virtual InfoHardware InfoHardware { get; set; }
        public virtual OrdersExecute OrdersExecute { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
