//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersExecute
    {
        public OrdersExecute()
        {
            this.OrdersFirms = new HashSet<OrdersFirm>();
            this.OrdersUsers = new HashSet<OrdersUser>();
        }
    
        public int Id { get; set; }
        public string message { get; set; }
    
        public virtual ICollection<OrdersFirm> OrdersFirms { get; set; }
        public virtual ICollection<OrdersUser> OrdersUsers { get; set; }
    }
}
