//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.OrdersUsers = new HashSet<OrdersUser>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }

        //  опируем из AccountModel вставл€ем над пол€ми класса
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<OrdersUser> OrdersUsers { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
